/**
 * Site content hierarchy for the DOS-like navigation system
 * Each page has an id, title, content lines, and optional children
 */

export interface SitePage {
  id: string;
  title: string;
  shortDesc: string;
  content: string[];
  /** Optional image shown below the text content. Will have CRT filter applied automatically. */
  image?: {
    src: string;
    alt: string;
    caption?: string;
  };
  children?: SitePage[];
}

export const siteTree: SitePage[] = [
  {
    id: 'home',
    title: 'HOME',
    shortDesc: 'Welcome screen',
    content: [
      '╔══════════════════════════════════════════════════════════════╗',
      '║              WELCOME TO RETRONET v2.1 ONLINE                ║',
      '║                  *** SYSTEM ONLINE ***                      ║',
      '╚══════════════════════════════════════════════════════════════╝',
      '',
      'Welcome, user. You have connected to RETRONET.',
      'This system provides access to information, services,',
      'and entertainment via the command-line interface.',
      '',
      'SYSTEM STATUS:',
      '  [OK] Memory: 640K conventional, 384K extended',
      '  [OK] Network: Connected at 9600 baud',
      '  [OK] Display: CGA 80x25 color mode',
      '  [OK] Sound: AdLib FM synthesizer detected',
      '',
      'Type HELP for a list of available commands.',
      'Type DIR to see available sections.',
      '',
      '──────────────────────────────────────────────────────────────',
      '"The future is already here — it\'s just not evenly distributed."',
      '                                          — William Gibson',
    ],
    children: [],
  },
  {
    id: 'about',
    title: 'ABOUT',
    shortDesc: 'About this system',
    content: [
      '╔══════════════════════════════════════════════════════════════╗',
      '║                    ABOUT RETRONET                           ║',
      '╚══════════════════════════════════════════════════════════════╝',
      '',
      'RETRONET is a retro-styled web experience built to evoke',
      'the golden age of personal computing (1980s-1990s).',
      '',
      'TECHNICAL SPECIFICATIONS:',
      '  Platform  : IBM PC Compatible',
      '  OS        : MS-DOS 6.22',
      '  Display   : VGA 80x25 text mode',
      '  Memory    : 640K base + 8MB extended',
      '  Network   : TCP/IP over dial-up modem',
      '  Sound     : Sound Blaster 16 compatible',
      '',
      'ABOUT THE CREATOR:',
      '  This system was lovingly crafted by a developer who',
      '  remembers when 640K was enough for anyone.',
      '',
      '  We believe the command line is the purest form of',
      '  human-computer interaction. No bloat. No distractions.',
      '  Just you and the machine.',
      '',
      'VERSION HISTORY:',
      '  v1.0  1991-03-15  Initial release',
      '  v1.5  1993-07-22  Added network support',
      '  v2.0  1995-11-01  GUI optional mode added',
      '  v2.1  1998-04-30  Y2K compliance update',
      '',
      'Type BACK to return to the previous menu.',
    ],
    children: [
      {
        id: 'about/history',
        title: 'HISTORY',
        shortDesc: 'System history',
        content: [
          '╔══════════════════════════════════════════════════════════════╗',
          '║                   SYSTEM HISTORY                            ║',
          '╚══════════════════════════════════════════════════════════════╝',
          '',
          'THE HISTORY OF RETRONET',
          '',
          '1989 — The idea is born in a university computer lab.',
          '       Two students, fueled by instant coffee and ambition,',
          '       sketch out a network of interconnected text terminals.',
          '',
          '1991 — Version 1.0 launches on a single 286 server.',
          '       First day: 12 users. First week: 847 users.',
          '       The BBS community takes notice.',
          '',
          '1993 — TCP/IP integration allows internet connectivity.',
          '       The system grows to 50,000 registered users.',
          '       First commercial advertisement appears (controversial).',
          '',
          '1995 — The "GUI Wars" begin. Some users demand graphics.',
          '       RETRONET holds firm: text is king.',
          '       A compromise: optional ANSI art mode.',
          '',
          '1998 — Y2K preparations consume six months of development.',
          '       The system survives January 1, 2000 without incident.',
          '',
          '2000+ — The web takes over. RETRONET becomes a museum piece.',
          '        But the faithful remain. The terminal never dies.',
          '',
          'Type BACK to return.',
        ],
      },
      {
        id: 'about/team',
        title: 'TEAM',
        shortDesc: 'The development team',
        content: [
          '╔══════════════════════════════════════════════════════════════╗',
          '║                    THE TEAM                                 ║',
          '╚══════════════════════════════════════════════════════════════╝',
          '',
          'CORE DEVELOPMENT TEAM:',
          '',
          '  SYSOP    : PHANTOM_CODER',
          '             Lead developer, network architect',
          '             "I speak fluent assembly."',
          '',
          '  CODENAME : NEON_GHOST',
          '             UI/UX designer (text-mode specialist)',
          '             "Every pixel is sacred."',
          '',
          '  HANDLE   : BYTE_WIZARD',
          '             Sound engine & hardware interfacing',
          '             "The beep is mightier than the GUI."',
          '',
          '  ALIAS    : CIRCUIT_SAGE',
          '             Security & network protocols',
          '             "Trust no packet."',
          '',
          'SPECIAL THANKS:',
          '  The entire BBS community of the early 90s.',
          '  Everyone who ever typed ATDT to connect.',
          '  The inventors of the blinking cursor.',
          '',
          'Type BACK to return.',
        ],
      },
    ],
  },
  {
    id: 'services',
    title: 'SERVICES',
    shortDesc: 'Available services',
    content: [
      '╔══════════════════════════════════════════════════════════════╗',
      '║                      SERVICES                               ║',
      '╚══════════════════════════════════════════════════════════════╝',
      '',
      'AVAILABLE SERVICES ON THIS SYSTEM:',
      '',
      '  [1] EMAIL      - Electronic mail system',
      '  [2] BULLETIN   - Public bulletin board',
      '  [3] FILES      - File download library',
      '  [4] CHAT       - Real-time chat rooms',
      '',
      'Navigate using: CD <service-name>',
      'Example: CD EMAIL',
      '',
      'All services require a valid user account.',
      'New users: type REGISTER to create an account.',
      '',
      'SYSTEM HOURS: 24/7 (except maintenance Sundays 2-4 AM)',
      '',
      'Type BACK to return to the previous menu.',
    ],
    children: [
      {
        id: 'services/email',
        title: 'EMAIL',
        shortDesc: 'Electronic mail',
        content: [
          '╔══════════════════════════════════════════════════════════════╗',
          '║                   EMAIL SYSTEM v3.2                         ║',
          '╚══════════════════════════════════════════════════════════════╝',
          '',
          'RETRONET ELECTRONIC MAIL',
          '',
          'INBOX: (3 new messages)',
          '──────────────────────────────────────────────────────────────',
          '  FROM              DATE        SUBJECT',
          '  ────────────────  ──────────  ──────────────────────────────',
          '  SYSOP@RETRONET    1998-04-30  Welcome to RETRONET!',
          '  NEON_GHOST        1998-04-29  Re: System upgrade',
          '  BYTE_WIZARD       1998-04-28  New sound drivers available',
          '──────────────────────────────────────────────────────────────',
          '',
          'COMMANDS:',
          '  READ <n>   - Read message number n',
          '  COMPOSE    - Write a new message',
          '  DELETE <n> - Delete message number n',
          '  BACK       - Return to services menu',
          '',
          'Storage used: 2.3 MB of 10 MB quota',
        ],
      },
      {
        id: 'services/bulletin',
        title: 'BULLETIN',
        shortDesc: 'Public bulletin board',
        content: [
          '╔══════════════════════════════════════════════════════════════╗',
          '║               PUBLIC BULLETIN BOARD                         ║',
          '╚══════════════════════════════════════════════════════════════╝',
          '',
          'RECENT POSTS:',
          '──────────────────────────────────────────────────────────────',
          '',
          '  [042] PHANTOM_CODER  1998-04-30',
          '        "System maintenance scheduled for Sunday."',
          '        Replies: 7',
          '',
          '  [041] NEON_GHOST     1998-04-29',
          '        "Anyone else notice the new ANSI art in the lobby?"',
          '        Replies: 12',
          '',
          '  [040] BYTE_WIZARD    1998-04-28',
          '        "AdLib vs Sound Blaster — the definitive thread"',
          '        Replies: 34',
          '',
          '  [039] CIRCUIT_SAGE   1998-04-27',
          '        "Security advisory: change your passwords"',
          '        Replies: 5',
          '',
          '──────────────────────────────────────────────────────────────',
          'Total posts: 1,337  |  Active users today: 42',
          '',
          'Type BACK to return.',
        ],
      },
      {
        id: 'services/files',
        title: 'FILES',
        shortDesc: 'File download library',
        content: [
          '╔══════════════════════════════════════════════════════════════╗',
          '║                  FILE LIBRARY v2.0                          ║',
          '╚══════════════════════════════════════════════════════════════╝',
          '',
          'AVAILABLE FILES:',
          '──────────────────────────────────────────────────────────────',
          '  FILENAME          SIZE    DATE        DESCRIPTION',
          '  ────────────────  ──────  ──────────  ──────────────────────',
          '  DOOM2.ZIP         2.1 MB  1994-10-10  DOOM II shareware',
          '  WOLF3D.ZIP        1.4 MB  1992-05-05  Wolfenstein 3D demo',
          '  QBASIC.EXE        512 KB  1991-06-01  QBasic interpreter',
          '  PKZIP204.EXE      52 KB   1993-02-01  PKZIP archiver',
          '  ANSIART.ZIP       340 KB  1995-08-15  ANSI art collection',
          '  MODEM_DRV.ZIP     128 KB  1997-11-20  Modem drivers pack',
          '  TETRIS.COM        8 KB    1990-01-01  Classic Tetris clone',
          '  README.TXT        2 KB    1998-04-30  System information',
          '──────────────────────────────────────────────────────────────',
          '',
          'Total files: 8  |  Total size: 4.5 MB',
          '',
          'Type BACK to return.',
        ],
      },
    ],
  },
  {
    id: 'portfolio',
    title: 'PORTFOLIO',
    shortDesc: 'Work showcase',
    content: [
      '╔══════════════════════════════════════════════════════════════╗',
      '║                      PORTFOLIO                              ║',
      '╚══════════════════════════════════════════════════════════════╝',
      '',
      'PROJECT SHOWCASE:',
      '',
      '  ► RETRONET CORE ENGINE',
      '    Language: C / Assembly',
      '    Year: 1991-1998',
      '    The backbone of this very system. 50,000 lines of',
      '    optimized C code with hand-tuned assembly routines.',
      '',
      '  ► ANSI TERMINAL RENDERER',
      '    Language: C++',
      '    Year: 1993',
      '    Full ANSI/VT100 escape code support with 256-color',
      '    palette mapping for CGA/EGA/VGA displays.',
      '',
      '  ► RETRONET SOUND ENGINE',
      '    Language: Assembly / C',
      '    Year: 1994',
      '    FM synthesis driver supporting AdLib, Sound Blaster,',
      '    and PC speaker. Procedural music generation.',
      '',
      '  ► PACKET RADIO INTERFACE',
      '    Language: C',
      '    Year: 1996',
      '    AX.25 protocol implementation for amateur radio',
      '    packet networking. 1200/9600 baud support.',
      '',
      'Type BACK to return to the previous menu.',
    ],
    image: {
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/IBM_PC_5150.jpg/960px-IBM_PC_5150.jpg',
      alt: 'IBM PC 5150 - the original IBM Personal Computer',
      caption: 'IBM PC 5150 (1981) — the machine that started it all.',
    },
    children: [],
  },
  {
    id: 'contact',
    title: 'CONTACT',
    shortDesc: 'Get in touch',
    content: [
      '╔══════════════════════════════════════════════════════════════╗',
      '║                       CONTACT                               ║',
      '╚══════════════════════════════════════════════════════════════╝',
      '',
      'HOW TO REACH US:',
      '',
      '  EMAIL    : sysop@retronet.bbs',
      '  FIDONET  : 1:234/567',
      '  USENET   : comp.bbs.retronet',
      '  IRC      : #retronet on EFnet',
      '  PHONE    : (555) 867-5309',
      '  FAX      : (555) 867-5310',
      '  MODEM    : (555) 867-5311  (9600 baud, 8N1)',
      '',
      'MAILING ADDRESS:',
      '  RETRONET Systems',
      '  P.O. Box 1337',
      '  Silicon Valley, CA 94025',
      '  United States of America',
      '',
      'SUPPORT HOURS:',
      '  Monday - Friday: 9:00 AM - 5:00 PM PST',
      '  Weekend: Emergency support only',
      '',
      'RESPONSE TIME:',
      '  Email: 24-48 hours',
      '  Fidonet: 2-3 days (netmail routing)',
      '  Snail mail: 2-3 weeks',
      '',
      'Type BACK to return to the previous menu.',
    ],
    children: [],
  },
];

/** Flatten the tree into a map for quick lookup */
export function buildPageMap(pages: SitePage[]): Map<string, SitePage> {
  const map = new Map<string, SitePage>();
  function traverse(page: SitePage) {
    map.set(page.id, page);
    if (page.children) {
      page.children.forEach(traverse);
    }
  }
  pages.forEach(traverse);
  return map;
}

/** Get all direct children of a given path */
export function getChildren(path: string, pages: SitePage[]): SitePage[] {
  if (path === '' || path === '/') {
    return pages;
  }
  const map = buildPageMap(pages);
  const page = map.get(path);
  return page?.children ?? [];
}

/** Get parent path */
export function getParentPath(path: string): string {
  const parts = path.split('/');
  if (parts.length <= 1) return '';
  parts.pop();
  return parts.join('/');
}
